[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
monke_core = { workspace = true }

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "benchmark"
harness = false
