[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
monke_core = { workspace = true }
byteorder = "1.5.0"
strum = "0.27.1"
strum_macros = "0.27.1"

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "benchmark"
harness = false
