[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
monke_core = { workspace = true }

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "benchmark"
harness = false
